# main configuration file
# Format is self-explanatory. Do not use quotes around multi-word values
[vendor]
# Vendor name. Short version, no spaces, lower case, e.g. island_robotics
VENDOR_NAME = envirodiy
# Full, human-readable vendor name, e.g. Island Robotics LLC
VENDOR_NAME_LONG = EnviroDIY
# Main webpage for your project. Among other things, used for
# "More info" link in Arduino board manager
INFO_URL = https://www.envirodiy.org/
# used for "online help" link in Arduino board manager. Should
# be a link to support forum if you have one; otherwise, just copy
# INFO_URL
HELP_URL = https://www.envirodiy.org/help/
MAINTAINER_NAME = Stroud Water Research Center - EnviroDIY
VENDOR_EMAIL = info@envirodiy.org

[package]
# name to use for your custom board support package, e.g.
# My New SAMD Board
# will be used by Board menu of Arduino IDE
PACKAGE_NAME = EnviroDIY SAMD Boards
# Package version
PACKAGE_VERSION = 0.4.0
# The repository where the package is maintained (ie, a git repository on GitHub).
PACKAGE_REPOSITORY = https://github.com/EnviroDIY/Arduino_boards
# Package base url for the zip archive - will have the zip archive name appended to it
# This is the location your archive will be hosted
PACKAGE_ARCHIVE_URL = https://github.com/EnviroDIY/Arduino_boards/raw/master/EnviroDIYSAMDBoards/
# URL to the json file with the package index, used for Arduino board manager
# Fill this out if you want to update an existing package based on a downloadable JSON file
# If you are creating a new package, leave this blank
PACKAGE_INDEX_URL = https://raw.githubusercontent.com/EnviroDIY/Arduino_boards/refs/heads/master/package_EnviroDIY_index.json
# Location of a local json file with the package index, used for Arduino board manager
# Fill this out if you want to update an existing package based on a local JSON file
# If you are creating a new package or want to update based on the URL above, leave this blank
PACKAGE_INDEX_FILE = C:/Users/sdamiano/Documents/GitHub/EnviroDIY/Arduino_boards/package_envirodiy_index.json
# DEFINE_NAME is used to set a compile-time macro with the package version, which can be used in your code to check for package version
# if you leave this blank, the package name will be used, but converted to upper case and with non-alphanumeric characters replaced by underscores
PACKAGE_DEFINE_NAME = ENVIRODIY_SAMD_BOARDS

[paths]
BUILD_OS = Windows
# Path to your arduino15 folder, containing hardware packages etc
# relative to your home directory
# Depending on your system, it can be:
# windows: AppData/Local/Arduino15
# MacOS:   Library/Arduino15
# Linux:   .arduino15
#
# See https://support.arduino.cc/hc/en-us/articles/360018448279-Open-the-Arduino15-folder
# do not include /Users/{username} (or equivalent on other systems)
# please use forward slashes (/) instead of  (\), even on Windows!
ARDUINO15 = AppData/Local/Arduino15

# path to folder containing GNU make utility. If it is already in PATH,
# comment this line
# If you installed GNU make for Windows from https://gnuwin32.sourceforge.net/packages/make.htm
# the path is likely C:/Program Files (x86)/GnuWin32/bin
# Under Linux or MacOS, the usual location is /usr/bin
MAKE_PATH = C:/Program Files (x86)/GnuWin32/bin

# cSpell:words ifdefs myboard MSSEN DVARIANT DENABLE DARM DARDUINO DENVIRODIY MFLOAT MFPU POWERPIN PULLUP GCLK PINMUX UART
